### PR TITLE
Delete report-crash

### PR DESCRIPTION
**Pull request by ARandomlyGeneratedUsername**

### CODE REVIEW

**Review by explowz — CHANGES_REQUESTED** [review]
Sorry it took me so long to see your pull request. For some reason GitHub didn't notify me somebody made a pull request on one of my repositories.

In scripts/updater:
1. Format line 110 (align it with the one above it)
2. Lines 143-149 are not needed. nproc --all is a much better way of getting the number of processors of a CPU, unless you can explain to me why getting it from cpuinfo is better. In essence it does the same thing, without the need to write extra lines of code to get it. And also why does auto updating only have to use 1 core? It'll just take longer and it's not like compiling this is going to fry anybody's CPU.

**Comment by ARandomlyGeneratedUsername** [comment]
> Sorry it took me so long to see your pull request. For some reason GitHub didn't notify me that somebody made a pull request on one of my repositories.
> 
> In scripts/updater:
> 
>     1. Format line 110 (align it with the one above it)
> 
>     2. Lines 143-149 are not needed. nproc --all is a much better way of getting the number of processors of a CPU, unless you can explain to me why getting it from cpuinfo is better. In essence it does the same thing, without the need to write extra lines of code to get it. And also why does auto updating only have to use 1 core? It'll just take longer and it's not like compiling this is going to fry anybody's CPU.

The only CPU that can be fried is mine :(

**Comment by explowz** [comment]
Still, I request you make the changes I asked you in the 2 comments above. What you made doesn't even always use 1 processor. It uses 1 processor only if the update is made by autoupdate. Manually updating cathook would still always use all processors.

**Review by explowz — APPROVED** [review]
Looks good to me

**Pull request merged**
